# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


r_to_json <- function(y_mean, tree_pnt) {
    .Call(`_XBCF_r_to_json`, y_mean, tree_pnt)
}

json_to_r <- function(json_string_r) {
    .Call(`_XBCF_json_to_r`, json_string_r)
}

sample_int_crank <- function(n, size, prob) {
    .Call(`_XBCF_sample_int_crank`, n, size, prob)
}

sample_int_ccrank <- function(n, size, prob) {
    .Call(`_XBCF_sample_int_ccrank`, n, size, prob)
}

sample_int_expj <- function(n, size, prob) {
    .Call(`_XBCF_sample_int_expj`, n, size, prob)
}

sample_int_expjs <- function(n, size, prob) {
    .Call(`_XBCF_sample_int_expjs`, n, size, prob)
}

XBCF_cpp <- function(y, X, X_tau, z, num_sweeps, burnin = 1L, max_depth = 1L, n_min = 5L, num_cutpoints = 1L, no_split_penality = 0.001, mtry_pr = 0L, mtry_trt = 0L, p_categorical_pr = 0L, p_categorical_trt = 0L, num_trees_pr = 200L, alpha_pr = 0.95, beta_pr = 2, tau_pr = 0.5, kap_pr = 16, s_pr = 4, pr_scale = FALSE, num_trees_trt = 50L, alpha_trt = 0.25, beta_trt = 3, tau_trt = 0.5, kap_trt = 16, s_trt = 4, trt_scale = FALSE, verbose = FALSE, parallel = TRUE, set_random_seed = FALSE, random_seed = 0L, sample_weights_flag = TRUE, a_scaling = TRUE, b_scaling = TRUE) {
    .Call(`_XBCF_XBCF_cpp`, y, X, X_tau, z, num_sweeps, burnin, max_depth, n_min, num_cutpoints, no_split_penality, mtry_pr, mtry_trt, p_categorical_pr, p_categorical_trt, num_trees_pr, alpha_pr, beta_pr, tau_pr, kap_pr, s_pr, pr_scale, num_trees_trt, alpha_trt, beta_trt, tau_trt, kap_trt, s_trt, trt_scale, verbose, parallel, set_random_seed, random_seed, sample_weights_flag, a_scaling, b_scaling)
}

